// lib/firebase_options.dart
// THIS FILE IS AUTO-GENERATED by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_PROJECT_ID
// Replace this file with the generated one.
//
// For local testing without Firebase, you can use Firebase Emulator Suite.
// See README.md for setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('${defaultTargetPlatform.name} not supported');
    }
  }

  // Real Firebase project values from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovsIvrrr7xYxMqKAZvqPoguj6gahNm-0',
    appId: '1:926159600645:android:8acf74e61c43524304306c',
    messagingSenderId: '926159600645',
    projectId: 'todo-app-9ec07',
    storageBucket: 'todo-app-9ec07.firebasestorage.app',
  );

  // Real Firebase project values from GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03uVEQAT53g2MnGrrhBPjU3DKRcaaKyU',
    appId: '1:926159600645:ios:ff239e596d1f3c4d04306c',
    messagingSenderId: '926159600645',
    projectId: 'todo-app-9ec07',
    storageBucket: 'todo-app-9ec07.firebasestorage.app',
    iosBundleId: 'com.avadh.todoApp',
  );
}
